"""whobuilt — write a credits file that names the people, not just the packages.

    python3 -m whobuilt .            # print it
    python3 -m whobuilt . --write    # save it as CREDITS.md

Every credits file lists packages. Packages didn't write themselves. This resolves each
dependency back through its registry to its source repository, and then to the handful of
humans with the most commits in it — and puts their names in your credits.

Public profile data only. Handles, and the display name someone chose to publish about
themselves. Nothing else.
"""

import argparse
import concurrent.futures
import os
import pathlib
import sys

from .resolve import resolve
from .scan import scan

LABEL = {"pypi": "Python", "npm": "JavaScript", "cargo": "Rust",
         "github": "Vendored source", "huggingface": "Model weights"}


def person(p):
    return f"[{p['name']}](https://github.com/{p['login']})" if p.get("name") \
        else f"[@{p['login']}](https://github.com/{p['login']})"


def render(project, results, thin, inferred=()):
    out = [f"# 🙏 Whose work {project} stands on", "",
           "None of this was written from scratch. These are the people whose work it "
           "rests on, generated by [whobuilt](https://github.com/nicedreamzapp/whobuilt) "
           "and worth reading rather than skipping.", ""]

    for kind in ("pypi", "npm", "cargo", "github", "huggingface"):
        rows = [r for r in results if r["kind"] == kind and (r["people"] or r["org"])
                and r["name"] not in inferred]
        if not rows:
            continue
        out += [f"## {LABEL[kind]}", ""]
        for r in sorted(rows, key=lambda x: -(x.get("stars") or 0)):
            link = f"[{r['name']}]({r['url']})" if r.get("url") else f"**{r['name']}**"
            desc = (r.get("summary") or "").strip().rstrip(".")
            head = f"**{link}**" + (f" — {desc}" if desc else "")
            out.append(f"- {head}")
            if r["people"]:
                names = ", ".join(person(p) for p in r["people"])
                more = " and everyone else who has contributed" if len(r["people"]) >= 4 else ""
                out.append(f"  <br>Built by {names}{more}.")
            elif r.get("org"):
                out.append(f"  <br>By **{r['org']}**.")
        out.append("")

    guessed = [r for r in results if r["name"] in inferred and (r["people"] or r["org"])]
    if guessed:
        out += ["## Guessed from imports — check these before you publish them", "",
                "This project has no dependency manifest, so these were inferred by reading "
                "`import` statements. An import name is not a package name, and PyPI is full "
                "of unrelated projects that happen to own a common word. **Some of these "
                "attributions are probably wrong.** Confirm each one, then move it up.", ""]
        for r in sorted(guessed, key=lambda x: -(x.get("stars") or 0)):
            link = f"[{r['name']}]({r['url']})" if r.get("url") else f"**{r['name']}**"
            desc = (r.get("summary") or "").strip().rstrip(".")
            out.append(f"- {link}" + (f" — {desc}" if desc else ""))
            if r["people"]:
                out.append("  <br>Possibly " + ", ".join(person(p) for p in r["people"]) + ".")
        out.append("")

    if thin:
        out += ["## Couldn't trace these", "",
                "These are used but I couldn't resolve them to a source repository, so "
                "nobody is named. That's a gap in this tool, not a judgement about the "
                "work.", "",
                "> " + ", ".join(sorted(thin)), ""]

    out += ["---", "",
            "If your work is listed here and you'd like the wording changed, or if "
            "something is missing or wrong, open an issue and it will be fixed.", ""]
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="whobuilt", description=__doc__.split("\n")[0])
    ap.add_argument("path", nargs="?", default=".")
    ap.add_argument("--write", action="store_true", help="save to CREDITS.md")
    ap.add_argument("-o", "--out", default="CREDITS.md")
    ap.add_argument("--depth", type=int, default=4)
    ap.add_argument("--max", type=int, default=60, help="cap on dependencies resolved")
    a = ap.parse_args(argv)

    root = os.path.abspath(os.path.expanduser(a.path))
    if not os.path.isdir(root):
        ap.error(f"not a directory: {a.path}")

    found, inferred = scan(root, a.depth)
    jobs = [(n, k) for k, names in found.items() for n in names][:a.max]
    if not jobs:
        print("No dependencies found. Nothing to credit — which is its own kind of "
              "achievement.", file=sys.stderr)
        return 0

    total = sum(len(v) for v in found.values())
    print(f"tracing {len(jobs)} of {total} dependencies back to their authors…",
          file=sys.stderr)

    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as ex:
        results = list(ex.map(lambda j: resolve(*j), jobs))

    thin = [r["name"] for r in results if not r["people"] and not r.get("org")]
    named = {p["login"] for r in results for p in r["people"]}
    print(f"{len(named)} people named across {len(results) - len(thin)} projects",
          file=sys.stderr)

    text = render(pathlib.Path(root).name, results, thin, inferred)
    if a.write:
        pathlib.Path(root, a.out).write_text(text)
        print(f"wrote {os.path.join(root, a.out)}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
